#!/bin/sh
set -e

case "$1" in
    purge)
        # Remove test results on purge
        rm -rf /var/lib/zabbix/mocha
        ;;
    remove)
        # Reload systemd
        systemctl daemon-reload || true
        ;;
esac

#DEBHELPER#

exit 0
